CREATE IF NOT EXISTS TABLE `AUTHOR` (
  `AUTHOR_ID` BIGINT NOT NULL,
  `FIRST_NAME` VARCHAR(45) NULL,
  `LAST_NAME` VARCHAR(45) NULL,
  `COUNTRY` VARCHAR(45) NULL,
  PRIMARY KEY (`AUTHOR_ID`));
  
CREATE IF NOT EXISTS TABLE `BOOK` (
  `bookId` BIGINT NOT NULL,
  `PAGE_COUNT` INT NULL,
  `PRICE` DECIMAL NULL,
  `PUBLISH_DATE` DATE NULL,
  `TITLE` VARCHAR(45) NULL,
  `AUTHOR_ID` BIGINT NULL,
  PRIMARY KEY (`bookId`),
  INDEX `FK1_idx` (`AUTHOR_ID` ASC),
  CONSTRAINT `FK1`
    FOREIGN KEY (`AUTHOR_ID`)
    REFERENCES `AUTHOR` (`AUTHOR_ID`)
    ON DELETE CASCADE
    ON UPDATE CASCADE);
